[DEBUG] 2021-09-21 16:53:58,167 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:53:58,173 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:54:58,252 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:54:58,258 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:54:58,306 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:54:58,311 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:54:58,315 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:55:58,390 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:55:58,396 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:55:58,446 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:55:58,451 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:55:58,456 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:56:58,529 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:56:58,535 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:56:58,584 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:56:58,589 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:56:58,593 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:57:58,671 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:57:58,677 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:57:58,727 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:57:58,732 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:57:58,737 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:58:58,811 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:58:58,815 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:58:58,864 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:58:58,869 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:58:58,873 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 16:59:58,950 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 16:59:58,956 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 16:59:59,005 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 16:59:59,010 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 16:59:59,015 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:00:59,092 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:00:59,097 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:00:59,154 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:00:59,159 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:00:59,164 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:01:59,241 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:01:59,247 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:01:59,297 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:01:59,302 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:01:59,307 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:02:59,377 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:02:59,382 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:02:59,432 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:02:59,436 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:02:59,441 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:03:59,514 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:03:59,520 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:03:59,571 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:03:59,576 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:03:59,582 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:04:59,654 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:04:59,660 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:04:59,711 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:04:59,716 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:04:59,720 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:05:59,795 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:05:59,801 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:05:59,848 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:05:59,853 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:05:59,857 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:06:59,925 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:06:59,930 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:06:59,979 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:06:59,984 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:06:59,988 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:08:00,059 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:08:00,064 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:08:00,123 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:08:00,127 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:08:00,131 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:09:00,205 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:09:00,211 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:09:00,261 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:09:00,266 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:09:00,270 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:10:00,351 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:10:00,356 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:10:00,405 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:10:00,410 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:10:00,415 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:11:00,486 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:11:00,491 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:11:00,542 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:11:00,547 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:11:00,552 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[ERROR] 2021-09-21 17:12:01,027 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Exception in Enqueue Events for Site erp.sample
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 81, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 228, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 553, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.219' ([Errno 101] Network is unreachable)")

[ERROR] 2021-09-21 17:12:01,029 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Exception in Enqueue Events for Site foo.bar
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 81, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 228, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 553, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.219' ([Errno 101] Network is unreachable)")

[ERROR] 2021-09-21 17:12:01,030 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Exception in Enqueue Events for Site gourmet.nerp
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 81, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 228, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 553, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")

[ERROR] 2021-09-21 17:12:01,032 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Exception in Enqueue Events for Site gourmet.nrp
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 81, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 228, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 553, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.219' ([Errno 101] Network is unreachable)")

[ERROR] 2021-09-21 17:12:01,033 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Exception in Enqueue Events for Site local.nerp
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 81, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 228, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 553, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.219' ([Errno 101] Network is unreachable)")

[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Site: gourmet.nerp
Form Dict: {
 "doctype": "Custom Script",
 "fields": "[\"`tabCustom Script`.`name`\",\"`tabCustom Script`.`owner`\",\"`tabCustom Script`.`creation`\",\"`tabCustom Script`.`modified`\",\"`tabCustom Script`.`modified_by`\",\"`tabCustom Script`.`_user_tags`\",\"`tabCustom Script`.`_comments`\",\"`tabCustom Script`.`_assign`\",\"`tabCustom Script`.`_liked_by`\",\"`tabCustom Script`.`docstatus`\",\"`tabCustom Script`.`parent`\",\"`tabCustom Script`.`parenttype`\",\"`tabCustom Script`.`parentfield`\",\"`tabCustom Script`.`idx`\",\"`tabCustom Script`.`dt`\"]",
 "filters": "[]",
 "order_by": "`tabCustom Script`.`modified` desc",
 "page_length": "20",
 "start": "0",
 "view": "List",
 "with_comment_count": "true"
}
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,095 | /home/attiq/frappe-bench/apps/frappe/frappe/app.py:
Site: gourmet.nerp
Site: gourmet.nerp
Site: gourmet.nerp
Request Error
Traceback (most recent call last):
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.get_user_info()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/auth.py", line 149, in get_user_info
    ["user_type", "first_name", "last_name", "user_image"], as_dict=1)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/attiq/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/attiq/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.79' ([Errno 101] Network is unreachable)")
[ERROR] 2021-09-21 17:12:02,194 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-09-21 17:12:02.101505-127.0.0.1-113
[ERROR] 2021-09-21 17:12:02,200 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-09-21 17:12:02.100112-127.0.0.1-b9b
[ERROR] 2021-09-21 17:12:02,200 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-09-21 17:12:02.096647-127.0.0.1-0b7
[ERROR] 2021-09-21 17:12:02,201 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-09-21 17:12:02.096844-127.0.0.1-a6f
[DEBUG] 2021-09-21 17:13:01,109 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:13:01,114 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:13:01,211 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:13:01,234 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:13:01,240 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:14:01,313 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:14:01,318 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:14:01,364 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:14:01,367 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:14:01,371 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:15:01,448 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:15:01,453 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:15:01,501 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:15:01,506 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:15:01,510 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:16:01,589 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:16:01,595 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:16:01,659 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:16:01,663 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:16:01,666 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:17:01,743 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:17:01,748 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:17:01,796 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:17:01,800 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:17:01,805 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:18:01,879 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:18:01,884 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:18:01,933 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:18:01,938 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:18:01,943 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:19:02,020 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:19:02,026 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:19:02,072 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:19:02,077 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:19:02,081 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:20:02,152 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:20:02,157 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:20:02,231 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:20:02,238 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:20:02,244 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:21:02,319 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:21:02,324 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:21:02,376 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:21:02,381 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:21:02,385 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:22:02,463 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:22:02,468 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:22:02,506 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:22:02,511 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:22:02,515 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:23:02,590 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:23:02,596 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:23:03,638 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:23:03,643 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:23:03,647 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:24:03,747 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:24:03,752 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:24:03,819 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:24:03,823 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:24:03,827 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:25:03,904 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:25:03,908 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:25:03,959 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:25:03,964 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:25:03,969 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:26:04,046 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:26:04,051 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:26:04,091 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:26:04,095 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:26:04,099 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:27:04,178 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:27:04,184 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:27:04,235 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:27:04,283 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:27:04,289 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:28:04,367 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:28:04,372 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:28:04,444 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:28:04,448 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:28:04,451 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:29:04,493 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:29:04,499 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:29:04,558 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:29:04,724 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:29:04,731 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:30:04,810 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:30:04,816 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:30:04,867 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:30:04,872 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:30:04,877 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:31:04,953 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:31:04,959 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:31:05,018 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:31:05,023 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:31:05,229 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:32:05,303 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:32:05,308 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:32:05,573 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:32:05,577 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:32:05,581 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:33:05,658 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:33:05,664 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:33:05,713 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:33:05,717 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:33:05,722 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:34:05,799 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:34:05,805 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:34:05,855 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:34:05,859 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:34:05,864 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:35:05,940 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:35:05,944 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:35:05,992 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:35:05,997 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:35:06,001 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:36:06,077 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:36:06,082 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:36:06,146 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:36:06,150 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:36:06,154 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:37:06,229 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:37:06,235 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:37:06,286 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:37:06,291 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:37:06,296 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:38:06,375 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:38:06,380 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:38:06,425 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:38:06,460 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:38:06,466 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:39:06,544 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:39:06,550 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:39:06,599 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:39:06,604 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:39:06,609 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:40:06,686 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:40:06,691 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:40:07,764 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:40:07,768 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:40:07,779 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:41:07,850 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:41:07,855 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:41:07,904 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:41:07,909 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:41:07,913 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:42:07,985 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:42:07,990 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:42:08,030 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:42:08,280 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:42:08,285 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:43:08,446 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:43:08,451 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:43:08,500 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:43:08,570 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:43:08,575 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:44:08,648 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:44:08,653 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:44:08,721 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:44:08,725 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:44:08,729 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:45:08,802 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:45:08,807 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:45:08,854 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:45:08,858 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:45:08,862 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:46:08,941 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:46:08,946 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:46:08,993 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:46:08,998 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:46:09,003 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:47:09,076 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:47:09,081 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:47:09,133 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:47:09,138 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:47:09,143 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:48:09,222 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:48:09,227 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:48:09,282 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:48:09,285 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:48:09,289 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:49:09,361 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:49:09,367 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:49:09,417 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:49:09,476 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:49:09,481 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:50:09,552 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:50:09,557 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:50:09,605 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:50:09,610 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:50:09,615 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:51:09,693 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:51:09,698 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:51:09,745 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:51:09,750 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:51:09,754 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:52:09,839 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:52:09,844 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:52:09,911 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:52:09,915 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:52:09,918 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:53:09,997 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:53:10,003 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:53:10,056 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:53:10,060 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:53:10,065 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:54:10,144 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:54:10,149 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:54:10,200 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:54:10,205 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:54:10,210 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:55:10,287 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:55:10,292 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:55:10,340 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:55:10,345 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:55:10,349 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:56:10,427 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:56:10,432 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:56:10,494 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:56:10,498 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:56:10,502 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:57:10,579 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:57:10,584 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:57:10,620 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:57:10,624 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:57:10,628 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:58:10,706 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:58:10,712 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:58:10,762 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:58:10,767 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:58:10,771 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 17:59:10,849 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 17:59:10,854 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 17:59:10,899 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 17:59:10,904 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 17:59:10,909 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 18:00:10,985 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 18:00:10,991 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 18:00:11,068 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 18:00:11,071 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 18:00:11,075 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 18:01:11,169 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 18:01:11,174 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 18:01:11,212 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 18:01:11,217 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 18:01:11,223 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 18:02:11,303 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 18:02:11,309 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 18:02:11,407 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 18:02:11,413 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 18:02:11,419 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 18:03:11,501 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 18:03:11,507 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 18:03:11,617 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 18:03:11,622 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
[DEBUG] 2021-09-21 18:03:11,628 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: local.nerp
Access denied for site local.nerp
[DEBUG] 2021-09-21 18:04:11,709 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: erp.sample
Access denied for site erp.sample
[DEBUG] 2021-09-21 18:04:11,714 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: foo.bar
Access denied for site foo.bar
[DEBUG] 2021-09-21 18:04:11,766 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nerp
Queued events for site gourmet.nerp
[DEBUG] 2021-09-21 18:04:11,770 | /home/attiq/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: gourmet.nrp
Access denied for site gourmet.nrp
